name:                haskell-clean-architecture
version:             0.1.0.0
github:              "err0r500/haskell-clean-arch-realworld-app"
license:             GPL-3
author:              "err0r500"
description:         Please see the README on GitHub at <https://github.com/err0r500/haskell-clean-architecture#readme>

dependencies:
  - base
  - rio
  - data-has

  # the logger
  - katip

  # the http servers
  - scotty
  - servant-server

  - wai
  - wai-extra
  - warp
  - http-types
  - mtl
  - aeson

  # storage
  - hasql
  - hasql-th
  - postgresql-error-codes

  # various utilities
  - uuid
  - email-validate

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - ConstraintKinds
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - RankNTypes
  - MonoLocalBinds

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  haskell-clean-architecture-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -static
      - -optl=-static
    dependencies:
      - haskell-clean-architecture

tests:
  haskell-clean-architecture-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec-discover
      - hspec
      - hspec-wai
      - hspec-wai-json
      - haskell-clean-architecture
